"""Base transform abstractions.

Defines the contract for all OSINT transforms in VESTIGIUM.
"""

from __future__ import annotations

import abc
from typing import Any, Sequence

from pydantic import BaseModel, Field


class TransformParam(BaseModel):
    """Metadata for a transform configurable parameter."""

    name: str
    display_name: str
    param_type: str = "string"  # string, integer, boolean, select
    description: str | None = None
    required: bool = False
    default: Any = None
    options: list[str] | None = None


class TransformResultItem(BaseModel):
    """A single output item generated by a transform.

    Specifies either a target entity to be created/linked or a property to update.
    """

    entity_type: str
    value: str
    label: str | None = None
    relationship_type: str = "related_to"
    relationship_label: str | None = None
    properties: dict[str, Any] = Field(default_factory=dict)
    confidence: float = 1.0
    color: str | None = None
    icon: str | None = None


class TransformResponse(BaseModel):
    """Container for results returned by a transform execution."""

    results: list[TransformResultItem] = Field(default_factory=list)
    raw_output: dict[str, Any] | str | None = None
    error_message: str | None = None
    is_success: bool = True


class BaseTransform(abc.ABC):
    """Abstract Base Class for all VESTIGIUM transforms.

    Transforms take an input entity (and optional configuration params)
    and produce output entities and relationships.
    """

    id: str
    name: str
    description: str
    category: str = "General"
    author: str = "Core Team"
    version: str = "1.0.0"
    source: str = "VESTIGIUM"
    documentation_url: str | None = None
    license: str = "MIT"

    input_entity_types: list[str]
    output_entity_types: list[str]
    relationships_created: list[str] = []
    params: list[TransformParam] = []

    # Execution Profile
    execution_type: str = "local"  # local, api, binary, container
    passive_or_active: str = "PASSIVE"  # PASSIVE, LOW_IMPACT, ACTIVE_AUTHORIZED
    is_passive: bool = True  # Legacy compat
    authorization_required: bool = False
    
    # Requirements
    api_key_required: bool = False
    requires_api_key: bool = False  # Legacy compat
    api_key_service: str | None = None
    installation_required: bool = False
    supported_os: list[str] = ["linux", "windows", "macos"]

    # Health & Availability
    is_active: bool = True
    availability_status: str = "AVAILABLE" # AVAILABLE, AVAILABLE_WITH_API_KEY, AVAILABLE_WITH_CONFIGURATION, NOT_INSTALLED, NOT_CONFIGURED, UNAVAILABLE, FAILED_HEALTH_CHECK, DISABLED
    install_status: str = "installed"  # Legacy compat
    installed_version: str | None = None
    configuration_status: str = "CONFIGURED"

    # Engine Constraints
    rate_limit: str | None = None
    timeout: int = 15
    supports_recursive_investigation: bool = True

    def check_availability(self, configured_keys: set[str] | None = None) -> str:
        """Dynamically evaluate availability based on binary presence and API key configuration.

        Args:
            configured_keys: Set of active API key service names from vault.

        Returns:
            The calculated availability status string.
        """
        import shutil
        configured_keys = configured_keys or set()

        if not self.is_active:
            self.availability_status = "DISABLED"
            return self.availability_status

        # 1. Binary / Installation check
        if self.installation_required or self.execution_type == "binary":
            bin_name = getattr(self, "binary_name", None) or self.id.split(".")[-1]
            found_path = shutil.which(bin_name)
            if not found_path:
                self.availability_status = "NOT_INSTALLED"
                self.install_status = "not_installed"
                return self.availability_status
            else:
                self.install_status = "installed"

        # 2. API key requirement check
        if self.api_key_required or self.requires_api_key:
            service = self.api_key_service or self.id.split(".")[-1]
            if service not in configured_keys:
                self.availability_status = "AVAILABLE_WITH_API_KEY"
                self.configuration_status = "NOT_CONFIGURED"
                return self.availability_status
            else:
                self.configuration_status = "CONFIGURED"

        self.availability_status = "AVAILABLE"
        return self.availability_status

    @abc.abstractmethod
    async def execute(
        self,
        entity: Any,
        params: dict[str, Any],
    ) -> tuple[list[Any], list[Any], dict[str, Any]]:
        """Execute the transform operation asynchronously.

        Args:
            entity: The input Entity model instance.
            params: User-provided parameter values matching self.params

        Returns:
            A tuple of (entities, relationships, raw_data)
        """
        pass
