"""Wafw00f transform adapter for Web Application Firewall (WAF) detection."""

from __future__ import annotations

import asyncio
import logging
import shutil
from typing import Any

import httpx

from app.models.entity import Entity
from app.models.relationship import EntityRelationship
from app.transforms.base import BaseTransform

logger = logging.getLogger(__name__)

# Built-in WAF signatures
WAF_SIGNATURES = [
    {"name": "Cloudflare WAF", "headers": ["cf-ray", "__cfduid", "cf-cache-status"], "cookies": ["__cfduid"], "body": ["cloudflare-nginx", "attention required! | cloudflare"]},
    {"name": "AWS WAF", "headers": ["x-amzn-requestid", "x-amz-cf-id", "x-amzn-waf-action"], "body": ["awswaf"]},
    {"name": "Akamai WAF / Kona Site Defender", "headers": ["x-akamai-transformed", "akamai-origin-hop"], "body": ["akamai"]},
    {"name": "Imperva Incapsula", "headers": ["x-cdn: incapsula", "x-iinfo"], "cookies": ["incap_ses", "visid_incap"], "body": ["incapsula incident"]},
    {"name": "ModSecurity / OWASP CRS", "headers": ["mod_security", "modsecurity"], "body": ["this error was generated by mod_security"]},
    {"name": "Sucuri CloudProxy", "headers": ["x-sucuri-id", "x-sucuri-cache"], "body": ["access denied - sucuri website firewall"]},
    {"name": "F5 BIG-IP ASM", "headers": ["x-cnection: close", "bigipserver"], "cookies": ["bigipserver"]},
    {"name": "Fastly WAF", "headers": ["x-fastly-request-id", "fastly-ssl"], "body": ["fastly error"]},
    {"name": "Wordfence Security", "body": ["generated by wordfence", "your access to this site has been limited by wordfence"]},
]


class Wafw00fTransform(BaseTransform):
    """Web Application Firewall (WAF) & Security Product Detector."""

    id = "builtin.wafw00f"
    name = "Wafw00f WAF Detector"
    description = "Identify Web Application Firewalls (WAFs) protecting the target (Cloudflare, AWS WAF, Akamai, Imperva, ModSecurity)."
    category = "Website & Web Technology"
    author = "VESTIGIUM"
    version = "1.0.0"
    source = "Wafw00f / Security Probes"
    documentation_url = "https://github.com/EnableSecurity/wafw00f"
    license = "BSD-3-Clause"

    input_entity_types = ["domain", "website", "url", "subdomain"]
    output_entity_types = ["company", "service", "ioc"]
    relationships_created = ["protected_by"]

    execution_type = "binary"
    passive_or_active = "LOW_IMPACT"
    is_passive = False
    authorization_required = False
    api_key_required = False
    installation_required = False  # Built-in WAF signature engine fallback
    supported_os = ["linux", "windows", "macos"]

    availability_status = "AVAILABLE"
    configuration_status = "CONFIGURED"
    timeout = 15
    supports_recursive_investigation = False

    async def execute(
        self,
        entity: Entity,
        params: dict[str, Any],
    ) -> tuple[list[Entity], list[EntityRelationship], dict[str, Any]]:
        target = entity.value.strip()
        if not target.startswith("http://") and not target.startswith("https://"):
            target_url = f"https://{target}"
        else:
            target_url = target

        detected_wafs: set[str] = set()

        # 1. Try wafw00f binary if available
        bin_path = shutil.which("wafw00f")
        if bin_path:
            try:
                proc = await asyncio.create_subprocess_exec(
                    bin_path,
                    "-a",
                    target_url,
                    stdout=asyncio.subprocess.PIPE,
                    stderr=asyncio.subprocess.PIPE,
                )
                stdout, _ = await asyncio.wait_for(proc.communicate(), timeout=self.timeout)
                if stdout:
                    text_out = stdout.decode("utf-8", errors="ignore")
                    for line in text_out.splitlines():
                        if "is behind" in line:
                            waf_name = line.split("is behind")[-1].strip()
                            detected_wafs.add(waf_name)
            except Exception as e:
                logger.debug("Wafw00f CLI execution error: %s", e)

        # 2. Signature engine fallback (send normal and malicious-looking probe)
        if not detected_wafs:
            async with httpx.AsyncClient(timeout=8.0, verify=False, follow_redirects=True) as client:
                try:
                    # Normal request
                    resp_normal = await client.get(target_url)
                    headers_str = " ".join([f"{k.lower()}:{v.lower()}" for k, v in resp_normal.headers.items()])
                    cookies_str = " ".join([k.lower() for k in resp_normal.cookies.keys()])
                    body_normal = resp_normal.text.lower()

                    for sig in WAF_SIGNATURES:
                        # Check headers
                        if any(h.lower() in headers_str for h in sig.get("headers", [])):
                            detected_wafs.add(sig["name"])
                        # Check cookies
                        if any(c.lower() in cookies_str for c in sig.get("cookies", [])):
                            detected_wafs.add(sig["name"])
                        # Check body
                        if any(b.lower() in body_normal for b in sig.get("body", [])):
                            detected_wafs.add(sig["name"])

                    # If no WAF found yet, try simple benign test probe that often triggers WAF block
                    if not detected_wafs:
                        try:
                            resp_probe = await client.get(f"{target_url}/?id=1' OR '1'='1")
                            probe_headers = " ".join([f"{k.lower()}:{v.lower()}" for k, v in resp_probe.headers.items()])
                            probe_body = resp_probe.text.lower()
                            for sig in WAF_SIGNATURES:
                                if any(h.lower() in probe_headers for h in sig.get("headers", [])) or any(b.lower() in probe_body for b in sig.get("body", [])):
                                    detected_wafs.add(sig["name"])
                        except Exception:
                            pass
                except Exception as e:
                    logger.debug("WAF probe request error: %s", e)

        entities: list[Entity] = []
        relationships: list[EntityRelationship] = []

        if detected_wafs:
            for waf in detected_wafs:
                waf_ent = Entity(
                    entity_type="company",
                    value=waf,
                    label=f"WAF: {waf}",
                    confidence=0.95,
                    source="Wafw00f",
                    properties={"waf_name": waf, "target": target_url},
                )
                entities.append(waf_ent)
                relationships.append(
                    EntityRelationship(
                        source_entity_id=entity.id,
                        target_entity_id=waf_ent.id,
                        relationship_type="protected_by",
                        confidence=0.95,
                        source="Wafw00f",
                        label="security_waf",
                    )
                )
        else:
            # Add No-WAF indicator if clean
            no_waf_ent = Entity(
                entity_type="service",
                value=f"No WAF Detected on {target}",
                label="No WAF Detected (Direct Origin)",
                confidence=0.7,
                source="Wafw00f",
                properties={"target": target_url, "waf_detected": False},
            )
            entities.append(no_waf_ent)
            relationships.append(
                EntityRelationship(
                    source_entity_id=entity.id,
                    target_entity_id=no_waf_ent.id,
                    relationship_type="protected_by",
                    confidence=0.7,
                    source="Wafw00f",
                    label="origin_exposure",
                )
            )

        return entities, relationships, {
            "target": target_url,
            "detected_wafs": list(detected_wafs),
            "is_protected": len(detected_wafs) > 0,
        }
